apiVersion: v1
kind: Service
metadata:
  name: teste-kubenetes-service
spec:
  type: LoadBalancer
  selector:
    app: server-kubernetes
  ports:
    - protocol: TCP
      name: http-svc
      port: 3000
